import { lazy, Suspense, useEffect, useRef, useState, type CSSProperties } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Button } from '@maxhub/max-ui';
import { ArrowUpRight, ArrowRight, Clock3, MapPin, Users, Sparkles, Wallet, ChevronLeft, X, Check, SlidersHorizontal, Navigation, Heart, ThumbsDown, Copy, CalendarDays, Plus, Info, LoaderCircle, ExternalLink, Gamepad2, Palette, Trees, Dumbbell, Coffee, Music2, Film, RefreshCw, Link2, List, Map as MapIcon, Wand2 } from 'lucide-react';
import { api, ApiError } from './api';
import { initData, openExternal, share, startParam } from './bridge';
import { useAppStore } from './store';
import { WindowTimeline, GroupWindows } from './visuals';
const ResultsMap = lazy(() => import('./mapview'));
import { parseRequest } from '../../../packages/contracts/parse';
import { categories, categoryNames, presets, preferencesSchema, type Candidate, type Preferences, type SearchResult } from '../../../packages/contracts/index';
const icons: Record<string, typeof Gamepad2> = { games: Gamepad2, culture: Palette, walk: Trees, sport: Dumbbell, food: Coffee, music: Music2, cinema: Film };
const hh = (s: string) => new Date(s).toLocaleTimeString('ru-RU', { timeZone: 'Europe/Moscow', hour: '2-digit', minute: '2-digit' });
const money = (n: number) => n === 0 ? 'Бесплатно' : `${n.toLocaleString('ru-RU')} ₽`;
const day = (date = new Date()) => new Date(date.getTime() + 3 * 3600000).toISOString().slice(0, 10);
// Quarter-hour steps keep the picker short and always 24-hour, whatever the device locale.
const quarterTimes = Array.from({ length: 96 }, (_, i) => `${String(Math.floor(i / 4)).padStart(2, '0')}:${String((i % 4) * 15).padStart(2, '0')}`).concat('23:59');
const timeOptions = (current: string) => [...new Set([...quarterTimes, current])].sort();
const dayChoices = () => Array.from({ length: 8 }, (_, i) => { const d = day(new Date(Date.now() + i * 86400000)); return { d, label: i === 0 ? 'Сегодня' : i === 1 ? 'Завтра' : new Date(`${d}T12:00:00+03:00`).toLocaleDateString('ru-RU', { weekday: 'short', day: 'numeric', timeZone: 'Europe/Moscow' }) }; });
// Page start for TZ §29 time-to-result / time-to-select; each is reported once per visit.
const openedAt = performance.now(); const reported = new Set<string>();
const track = (kind: string, durationMs?: number) => { if (durationMs !== undefined) { if (reported.has(kind)) return; reported.add(kind); } void api('/metrics', 'POST', { kind, ...(durationMs !== undefined ? { durationMs: Math.round(durationMs) } : {}) }).catch(() => {}); };
const initialDate = () => { const d = new Date(); return new Date(`${day()}T18:30:00+03:00`).getTime() > Date.now() ? day() : day(new Date(d.getTime() + 86400000)); };

export function App() {
  const q = useQueryClient(); const s = useAppStore();
  const config = useQuery({ queryKey: ['config'], queryFn: () => api('/config') });
  const me = useQuery({ queryKey: ['me'], queryFn: () => api('/me') });
  const [notice, setNotice] = useState(''), [error, setError] = useState(''), [errorCode, setErrorCode] = useState(''), [busy, setBusy] = useState(false), [phase, setPhase] = useState(0);
  const [date, setDate] = useState(initialDate), [from, setFrom] = useState('18:30'), [to, setTo] = useState('21:30');
  const [budget, setBudget] = useState(1000), [travel, setTravel] = useState(30), [transport, setTransport] = useState(0), [origin, setOrigin] = useState<Preferences['origin']>({ ...presets[0], preset: presets[0].id });
  const [interests, setInterests] = useState<string[]>([]), [excluded, setExcluded] = useState<string[]>([]), [modeChoice, setModeChoice] = useState<'demo' | 'live' | null>(null),[context, setContext] = useState<'any' | 'calm' | 'active' | 'date'>('any');
  const [advanced, setAdvanced] = useState(false), [invite, setInvite] = useState<string | null>(null), [saved, setSaved] = useState<{ id: string; shareUrl: string } | null>(null), [groupTitle, setGroupTitle] = useState('После пар'), [linkInput, setLinkInput] = useState(''), [showExcluded, setShowExcluded] = useState(false), [view, setView] = useState<'list' | 'map'>('list'), [phrase, setPhrase] = useState('');
  const swipe = useRef<number | null>(null);
  // Real events are the default; test data is an explicit, clearly labelled choice at the bottom of the page.
  const liveAvailable = !!config.data?.liveAvailable, mode = modeChoice ?? (liveAvailable ? 'live' : 'demo');
  const resultsRef = useRef<HTMLElement>(null), dialogRef = useRef<HTMLDialogElement>(null), launched = useRef(false);
  const session = useQuery({ queryKey: ['session', s.sessionId], queryFn: () => api(`/sessions/${s.sessionId}`), enabled: !!s.sessionId && !!me.data, refetchInterval: 5000 });
  const inviteInfo = useQuery({ queryKey: ['invite', invite], queryFn: () => api(`/invites/${invite}`), enabled: !!invite && !!me.data });
  const stats = useQuery({ queryKey: ['stats'], queryFn: () => api('/stats?days=7'), enabled: s.screen === 'about', staleTime: 60000 });
  const quota = useQuery({ queryKey: ['quota'], queryFn: () => api('/quota'), enabled: !!me.data && mode === 'live' });
  const authenticated = !!me.data;
  useEffect(() => { window.WebApp?.ready?.(); window.WebApp?.expand?.(); }, []);
  useEffect(() => { if (!busy) return; const timer = setInterval(() => setPhase(p => (p + 1) % 4), 800); return () => clearInterval(timer); }, [busy]);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 6000); return () => clearTimeout(timer); }, [notice]);
  useEffect(() => { if (s.detail) track('card_open'); }, [s.detail?.event.id]);
  useEffect(() => { if (s.detail) dialogRef.current?.showModal(); else dialogRef.current?.close(); const back = () => s.setDetail(null); if (s.detail) { window.WebApp?.BackButton?.show(); window.WebApp?.BackButton?.onClick(back); } return () => { window.WebApp?.BackButton?.offClick(back); window.WebApp?.BackButton?.hide(); }; }, [s.detail]);
  useEffect(() => {
    if (!me.data || launched.current) return; launched.current = true;
    if (me.data.interests?.length) setInterests(me.data.interests);
    void api('/metrics', 'POST', { kind: 'app_open' }).catch(() => {});
    const params = new URLSearchParams(location.search), start = startParam();
    const group = params.get('session') || (start.startsWith('session_') ? start.slice(8) : null);
    const plan = params.get('plan') || (start.startsWith('plan_') ? start.slice(5) : null);
    const search = start.startsWith('search_') ? start.slice(7) : null;
    if (group) { setInvite(group); s.setScreen('group'); }
    if (plan) void run(async () => { const p = await api(`/plans/${plan}`); s.setDetail(p.candidate); setSaved({ id: plan, shareUrl: location.href }); });
    if (search) void run(async () => s.setResult(await api(`/search/${search}`)));
  }, [me.data]);
  useEffect(() => {
    const id = session.data?.searchId;
    if (id && id !== s.result?.id && session.data?.members?.find((m: any) => m.userId === me.data?.id)?.preferences?.dataMode !== 'live') void api<SearchResult>(`/search/${id}`).then(s.setResult).catch(() => {});
    if (session.data && !id && s.result) s.setResult(null);
  }, [session.data?.searchId]);
  async function run(action: () => Promise<unknown>) { setError(''); setErrorCode(''); setBusy(true); try { await action(); } catch (e) { setError(e instanceof Error ? e.message : 'Нет соединения. Попробуйте ещё раз'); setErrorCode(e instanceof ApiError ? e.code : ''); } finally { setBusy(false); } }
  function switchMode(next: 'demo' | 'live') { setModeChoice(next); s.setResult(null); setError(''); setErrorCode(''); setNotice(next === 'demo' ? 'Включены тестовые данные: учебные события, не настоящая афиша' : 'Снова реальные события KudaGo и маршруты Яндекса'); }
  function preferences(): Preferences {
    const r = preferencesSchema.safeParse({ dataMode: mode, availableFrom: `${date}T${from}:00+03:00`, availableTo: `${date}T${to}:00+03:00`, budget, maxTravelMinutes: travel, transportBudget: transport, categories: interests, excludedCategories: excluded, origin, context });
    if (!r.success) throw new Error(r.error.issues[0].message); return r.data;
  }
  async function find() { await run(async () => { if (!authenticated) throw new Error('Подключаемся к сервису. Повторите через пару секунд'); const p = preferences(); await api('/me/interests', 'PUT', { interests }); s.setResult(null); const result = await api<SearchResult>('/search', 'POST', p); s.setResult(result); track('time_to_result', performance.now() - openedAt); setSaved(null); void q.invalidateQueries({ queryKey: ['quota'] }); setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 100); }); }
  function quick(kind: string) {
    setError('');
    if (kind === 'free') { setBudget(0); return; }
    if (kind === 'friends') { s.setScreen('group'); return; }
    if (kind === 'surprise') { setInterests([]); setExcluded([]); setContext('any'); setNotice('Открыты всем идеям. Время, бюджет и дорога остаются обязательными.'); return; }
    if (kind === 'evening') { setDate(initialDate()); setFrom('18:30'); setTo('21:30'); return; }
    const begin = new Date(Date.now() + 5 * 60000), end = new Date(begin.getTime() + (kind === 'now' ? 180 : 120) * 60000);
    setDate(day(begin)); setFrom(hh(begin.toISOString())); setTo(hh(end.toISOString())); if (day(begin) !== day(end)) setTo('23:59');
  }
  async function choose(c: Candidate) { await run(async () => { if (!s.result) return; const endpoint = s.screen === 'group' && s.sessionId ? `/sessions/${s.sessionId}/select` : '/plans'; const p = await api(endpoint, 'POST', { searchId: s.result.id, eventId: c.event.id }); setSaved(p); track('time_to_select', performance.now() - openedAt); s.setDetail(c); setNotice('План сохранён на 24 часа'); void q.invalidateQueries({ queryKey: ['session'] }); }); }
  async function locate() { if (mode === 'demo') { setNotice('Своя геопозиция работает с реальными данными. В тестовых данных есть четыре подготовленные точки.'); return; } await run(() => new Promise<void>((resolve, reject) => navigator.geolocation ? navigator.geolocation.getCurrentPosition(p => { setOrigin({ lat: p.coords.latitude, lon: p.coords.longitude, label: 'Моё местоположение' }); resolve(); }, () => reject(new Error('Геопозиция недоступна. Выберите метро или кампус')), { timeout: 10000, maximumAge: 30000 }) : reject(new Error('Геопозиция не поддерживается. Выберите точку из списка')))); }
  async function copy(value: string) { await run(async () => { await navigator.clipboard.writeText(value); setNotice('Ссылка скопирована'); }); }
  function applyPhrase() {
    const r = parseRequest(phrase), done: string[] = [];
    if (r.from && r.to) { setDate(day(new Date(r.from))); setFrom(hh(r.from)); setTo(day(new Date(r.to)) === day(new Date(r.from)) ? hh(r.to) : '23:59'); done.push(`${hh(r.from)}–${hh(r.to)}`); }
    if (r.budget !== undefined) { setBudget(r.budget); done.push(money(r.budget)); }
    if (r.maxTravelMinutes) { setTravel(r.maxTravelMinutes); done.push(`до ${r.maxTravelMinutes} мин`); }
    if (r.categories.length) { setInterests(r.categories); done.push(r.categories.map(c => categoryNames[c]).join(', ')); }
    if (r.excludedCategories.length) { setExcluded(r.excludedCategories); setAdvanced(true); done.push('без: ' + r.excludedCategories.map(c => categoryNames[c].toLowerCase()).join(', ')); }
    if (!done.length) { setError('Не понял фразу. Пример: «завтра вечером до 1500, игры, не дальше 30 минут»'); return; }
    setError(''); setNotice(`Заполнил: ${done.join(' · ')}. Проверь и нажми «Найти варианты»`);
  }
  function trackLink(url: string, kind: string) { void api('/metrics', 'POST', { kind }).catch(() => {}); openExternal(url); }
  const showError = error || (session.error ? session.error.message : '') || (inviteInfo.error ? inviteInfo.error.message : '');
  const title = s.screen === 'group' ? 'Хороший план — общий.' : s.screen === 'about' ? 'Время на то, что нравится.' : 'Есть окно? Есть планы.';
  const fieldForm = <>
    <div className="section-label"><span className="step">01</span> Когда ты свободен <span className="muted small">Московское время</span></div>
    <div className="day-chips" role="radiogroup" aria-label="Дата">{dayChoices().map(c => <button type="button" role="radio" aria-checked={date === c.d} key={c.d} className={`chip ${date === c.d ? 'active' : ''}`} onClick={() => setDate(c.d)}>{c.label}</button>)}</div>
    <div className="time-row two"><label>С<select aria-label="Свободен с" value={from} onChange={e => setFrom(e.target.value)}>{timeOptions(from).map(t => <option key={t}>{t}</option>)}</select></label><span className="time-dash">—</span><label>До<select aria-label="Свободен до" value={to} onChange={e => setTo(e.target.value)}>{timeOptions(to).map(t => <option key={t}>{t}</option>)}</select></label></div>
    <div className="section-label"><span className="step">02</span> Откуда выходим</div>
    <div className="location-row"><MapPin size={19}/><select aria-label="Точка старта" value={origin.preset ?? 'custom'} onChange={e => { const p = presets.find(p => p.id === e.target.value)!; setOrigin({ ...p, preset: p.id }); }}><option value="custom" disabled>Моё местоположение</option>{presets.map(p => <option value={p.id} key={p.id}>{p.label}</option>)}</select><button className="icon-button" type="button" aria-label="Моя геопозиция" onClick={locate}><Navigation size={19}/></button></div>
    <div className="two-fields"><label><span className="label-icon"><Wallet size={17}/> Бюджет на человека</span><div className="number-unit"><input aria-label="Бюджет на человека" type="number" min="0" max="50000" step="50" value={budget} onChange={e => setBudget(Number(e.target.value))}/><span>₽</span></div></label><label><span className="label-icon"><Clock3 size={17}/> Дорога в одну сторону</span><div className="number-unit"><input aria-label="Лимит дороги" type="number" min="5" max="120" step="5" value={travel} onChange={e => setTravel(Number(e.target.value))}/><span>мин</span></div></label></div>
    <div className="section-label"><span className="step">03</span> Чего хочется <span className="muted small">Можно несколько</span></div>
    <div className="interest-list">{categories.map(c => { const Icon = icons[c]; return <button key={c} type="button" className={`chip ${interests.includes(c) ? 'active' : ''}`} aria-pressed={interests.includes(c)} onClick={() => setInterests(a => a.includes(c) ? a.filter(x => x !== c) : [...a, c])}><Icon size={16}/>{categoryNames[c]}</button>; })}</div>
    <button type="button" className="text-button more" onClick={() => setAdvanced(!advanced)} aria-expanded={advanced}><SlidersHorizontal size={16}/> {advanced ? 'Свернуть настройки' : 'Проезд, настроение и исключения'}</button>
    {advanced && <div className="advanced"><label>Расходы на проезд туда и обратно, ₽<input aria-label="Расходы на проезд" type="number" min="0" max="10000" value={transport} onChange={e => setTransport(Number(e.target.value))}/><small>0 ₽ — если проезд покрыт проездным. Сумма входит в бюджет.</small></label><label>Настроение<select value={context} onChange={e => setContext(e.target.value as any)}><option value="any">Любое</option><option value="calm">Спокойно</option><option value="active">Активно</option><option value="date">Свидание</option></select></label><label>Не предлагать</label><div className="interest-list">{categories.map(c => <button type="button" key={c} className={`chip ${excluded.includes(c) ? 'excluded' : ''}`} onClick={() => setExcluded(a => a.includes(c) ? a.filter(x => x !== c) : [...a, c])}>{excluded.includes(c) && <X size={13}/>} {categoryNames[c]}</button>)}</div></div>}
  </>;
  const resultView = s.result && <section className="results" ref={resultsRef} aria-live="polite"><div className="section-heading"><div className="eyebrow">ТВОЁ СВОБОДНОЕ ВРЕМЯ</div><h2>{s.result.results.length ? `${s.result.results.length} идей, которые помещаются в окно` : 'Чуть больше свободы — и найдём'}</h2><p className="muted">{s.result.commonWindow ? `${hh(s.result.commonWindow.from)}–${hh(s.result.commonWindow.to)} · с дорогой туда и обратно` : 'У участников пока нет общего времени'}</p>{!!s.result.results.length && <div className="view-toggle" role="tablist" aria-label="Вид результатов"><button role="tab" aria-selected={view === 'list'} className={view === 'list' ? 'active' : ''} onClick={() => setView('list')}><List size={15}/> Список</button><button role="tab" aria-selected={view === 'map'} className={view === 'map' ? 'active' : ''} onClick={() => setView('map')}><MapIcon size={15}/> Карта</button></div>}</div>
    <div className="data-note"><Info size={17}/><div>{s.result.notices.map(n => <p key={n}>{n}</p>)}</div></div>
    {!s.result.results.length && <div className="empty-state"><Clock3 size={44}/><h3>Сейчас ни один вариант не проходит все условия</h3><p>Мы не будем предлагать то, на что ты не успеешь. Попробуй одно из проверенных изменений:</p><div className="interest-list">{s.result.compromises.map(c => <button className="chip" key={c.field} onClick={() => { if (c.field === 'budget') setBudget(v => Math.min(50000, v + c.value)); if (c.field === 'maxTravelMinutes') setTravel(v => Math.min(120, v + c.value)); if (c.field === 'availableTo') setTo(hh(new Date(Date.parse(`${date}T${to}:00+03:00`) + c.value * 60000).toISOString())); setNotice('Параметр изменён. Повторите подбор; в компании каждый обновляет свои ограничения.'); window.scrollTo({ top: 0, behavior: 'smooth' }); }}>{c.label} <span>→ {c.count}</span></button>)}</div>{!s.result.compromises.length && <p>Выбери другое окно или точку старта. Для реальных событий источник может не содержать точного расписания.</p>}</div>}
    {view === 'map' && !!s.result.results.length && <Suspense fallback={<div className="results-map loading"><LoaderCircle size={22} className="spin"/> Загружаем карту…</div>}><ResultsMap results={s.result.results} origin={s.screen === 'search' ? origin : undefined} onOpen={c => { s.setDetail(c); setSaved(null); }}/></Suspense>}
    <div className="cards" key={s.result.id}>{s.result.results.map((c, i) => <EventCard key={c.event.id} c={c} index={i} window={s.result!.commonWindow} onOpen={() => { s.setDetail(c); setSaved(null); }} onChoose={() => choose(c)} busy={busy}/>)}</div>
    {!!s.result.excluded.length && <div className="excluded-list"><button className="text-button" onClick={() => setShowExcluded(!showExcluded)}>{showExcluded ? 'Скрыть' : 'Почему скрыты'} {s.result.excluded.length} вариантов <Info size={15}/></button>{showExcluded && s.result.excluded.map(e => <div key={e.id}><span>{e.title}</span><small>{e.reasons.join(' · ')}</small></div>)}</div>}
  </section>;
  return <div className="app-shell">
    <aside className="sidebar"><button className="brand" onClick={() => s.setScreen('search')} aria-label="ОКНО — главная"><span className="brand-mark"><i/><i/><i/><i/></span>ОКНО<span className="brand-dot">.</span></button><p className="brand-caption">Время на своё</p><nav>{[{ id: 'search', icon: Sparkles, text: 'Найти досуг' }, { id: 'group', icon: Users, text: 'Моя компания' }, { id: 'about', icon: Info, text: 'Как это работает' }].map(n => <button key={n.id} className={s.screen === n.id ? 'selected' : ''} onClick={() => s.setScreen(n.id as any)}><n.icon size={20}/>{n.text}{n.id === 'group' && session.data && <span className="nav-count">{session.data.members.length}</span>}</button>)}</nav></aside>
    <main><header className="topbar"><div className="city"><MapPin size={15}/> Москва <span>•</span><span className="muted">Сегодня {new Date().toLocaleDateString('ru-RU', { day: 'numeric', month: 'long', timeZone: 'Europe/Moscow' })}</span></div><div className="profile"><span className="status-dot"/>{me.data ? me.data.name : 'Добро пожаловать'}<div className="avatar">{(me.data?.name || 'О')[0]}</div></div></header>
      <div className="page-content"><section className="hero"><div><div className="eyebrow">ДОСУГ БЕЗ ЛИШНИХ ПОИСКОВ</div><h1>{title}</h1><p>{s.screen === 'group' ? 'У каждого свои планы. Найдём время и место, которые подойдут всем.' : 'Расскажи, когда свободен. Мы подберём, куда успеть — одному или с друзьями.'}</p></div><div className="hero-art" aria-hidden="true"><div className="orbit"/><div className="window-art"><div className="window-top">свободное время <span>↗</span></div><div className="window-time">18:30<span>— 21:30</span></div><div className="window-bottom"><span className="spark">✳</span> место для нового</div></div><span className="art-sticker">ты успеешь!</span></div></section>
      {!authenticated && (initData() || me.isError) && <section className="auth-panel"><div><h3>{initData() ? 'Проверяем вход в MAX' : 'Не удалось подключиться'}</h3><p>{me.error?.message ?? 'Это займёт несколько секунд'}</p></div>{me.isError && (config.data?.guestAuth === false && !initData() ? <Button onClick={() => openExternal(`https://max.ru/${config.data.botUsername}?startapp`)}>Открыть в MAX</Button> : <Button disabled={me.isFetching} onClick={() => void me.refetch()}><RefreshCw size={16}/> Повторить</Button>)}</section>}
      <div className="alerts" aria-live="polite">{showError && <div className="error" role="alert"><Info size={18}/><span>{showError}</span>{error && mode === 'live' && ['RATE_LIMITED', 'ROUTE_PROVIDER_ERROR', 'EVENT_PROVIDER_ERROR'].includes(errorCode) && <button className="text-button" onClick={() => switchMode('demo')}>Показать на тестовых данных <ArrowRight size={14}/></button>}<button className="icon-button" aria-label="Закрыть ошибку" onClick={() => setError('')}><X size={16}/></button></div>}</div>
      {s.screen !== 'about' && <><div className="quick-actions"><button onClick={() => quick('now')}><Sparkles size={15}/> Прямо сейчас</button><button onClick={() => quick('two')}><Clock3 size={15}/> На пару часов</button><button onClick={() => quick('evening')}><CalendarDays size={15}/> После пар</button><button onClick={() => quick('free')}><Wallet size={15}/> Бесплатно</button><button onClick={() => quick('friends')}><Users size={15}/> С друзьями</button><button onClick={() => quick('surprise')}>Удиви меня <ArrowUpRight size={15}/></button></div>
        {mode === 'demo' && config.data && <div className="mode-row"><div className="mode-badge demo"><span className="status-dot"/>Тестовые данные</div><span className="muted small">Учебные события, цены и время в пути — не настоящая афиша.{liveAvailable ? ' Вернуть реальные события можно внизу страницы.' : ''}</span></div>}
        {s.screen === 'group' && <section className="group-panel"><div className="section-label"><Users size={21}/> {session.data?.title ?? 'Соберите компанию'}</div>
          {invite && !s.sessionId && <div className="invite-banner"><h3>Приглашение: {inviteInfo.data?.title ?? 'Пойдём вместе'}</h3><p>{inviteInfo.data?.memberCount ?? '…'} из 5 мест занято. Твоя точная геопозиция другим участникам не показывается.</p><Button disabled={busy || !authenticated} onClick={() => run(async () => { await api(`/sessions/${invite}/join`, 'POST'); s.setSession(invite); setInvite(null); })}>Присоединиться</Button></div>}
          {!s.sessionId && !invite && <div className="group-create"><label>Название компании<input value={groupTitle} maxLength={80} onChange={e => setGroupTitle(e.target.value)} placeholder="После пар"/></label><Button disabled={busy || !authenticated} onClick={() => run(async () => { const group = await api('/sessions', 'POST', { title: groupTitle || 'Пойдём вместе' }); s.setSession(group.id); })}><Plus size={17}/> Создать компанию</Button><div className="join-link"><input aria-label="Ссылка приглашения" placeholder="Или вставь ссылку приглашения" value={linkInput} onChange={e => setLinkInput(e.target.value)}/><button className="text-button" onClick={() => { const id = linkInput.match(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i)?.[0]; if (id) setInvite(id); else setError('Вставьте полную ссылку приглашения'); }}>Открыть</button></div></div>}
          {session.data && <><div className="members">{session.data.members.map((m: any, i: number) => <div key={m.userId}><span className={`member-avatar a${i}`}>{m.name[0]}</span><span>{m.name}{m.userId === me.data?.id ? ' (ты)' : ''}<small>{m.ready ? 'Параметры готовы' : 'Выбирает параметры'}</small></span>{m.ready ? <Check size={18} className="green"/> : <Clock3 size={18} className="muted"/>}</div>)}</div><GroupWindows members={session.data.members} meId={me.data?.id}/><div className="group-actions"><Button variant="secondary" onClick={() => share(session.data.inviteUrl, 'Пойдём вместе! Укажи своё окно в ОКНО')}><Link2 size={17}/> Пригласить в MAX</Button><button className="icon-button" aria-label="Скопировать приглашение" onClick={() => copy(session.data.inviteUrl)}><Copy size={18}/></button><button className="text-button" onClick={() => { s.setSession(null); s.setResult(null); setInvite(null); }}>Другая компания</button></div><p className="muted small">До 5 участников · ссылка действует 24 часа · обновление статусов каждые 5 секунд</p></>}
        </section>}
        {s.screen === 'search' && <form className="phrase" onSubmit={e => { e.preventDefault(); applyPhrase(); }}><Wand2 size={19}/><input aria-label="Опиши вечер одной фразой" placeholder="Опиши вечер одной фразой: «завтра после пар на 2 часа до 1000, не кино»" value={phrase} maxLength={200} onChange={e => setPhrase(e.target.value)}/><button className="text-button" type="submit" disabled={!phrase.trim()}>Заполнить <ArrowRight size={15}/></button></form>}
        <div className="planner-layout"><form className="planner" onSubmit={e => { e.preventDefault(); if (s.screen === 'group') void run(async () => { if (!s.sessionId) throw new Error('Сначала создайте компанию или присоединитесь'); const p = preferences(); await api('/me/interests', 'PUT', { interests }); await api(`/sessions/${s.sessionId}/preferences`, 'PUT', p); await q.invalidateQueries({ queryKey: ['session'] }); setNotice('Твои параметры сохранены'); }); else void find(); }}><div className="planner-heading"><h2>{s.screen === 'group' ? 'Твоё окно в общем плане' : 'Каким будет твоё окно?'}</h2><span>≈ 30 секунд</span></div>{fieldForm}<Button className="find-button" type="submit" stretched size="large" disabled={busy || !authenticated || !config.data}>{busy ? <><LoaderCircle size={19} className="spin"/>{['Ищем события…', 'Проверяем время…', 'Считаем дорогу…', 'Подбираем лучшее…'][phase]}</> : <>{s.screen === 'group' ? 'Сохранить мои параметры' : 'Найти варианты'}<ArrowRight size={19}/></>}</Button><p className="form-footnote"><Check size={14}/> Учитываем возвращение и 10 минут запаса</p></form>
        <aside className="plan-aside"><div className="mini-heading">СВОБОДНОЕ ВРЕМЯ — ТВОЁ</div><h2>Меньше выбирать.<br/>Больше проживать.</h2><div className="timeline-preview"><div><span className="timeline-icon"><MapPin size={18}/></span><p>{from}<small>Выход из твоей точки</small></p></div><div><span className="timeline-icon purple"><Sparkles size={18}/></span><p>Что-то хорошее<small>Время для нового впечатления</small></p></div><div><span className="timeline-icon"><Check size={18}/></span><p>До {to}<small>Возвращение без спешки</small></p></div></div><div className="assurance"><span className="large-star">✳</span><p>Сначала проверяем,<br/>что ты успеешь.<br/><strong>Потом рекомендуем.</strong></p></div><div className="small muted">Не хватает времени или бюджета?<br/>Предложим конкретный компромисс.</div></aside></div>
        {s.screen === 'group' && s.sessionId && <div className="group-search"><Button size="large" disabled={busy || session.data?.ownerId !== me.data?.id || !session.data?.members?.every((m: any) => m.ready)} onClick={() => run(async () => { const result = await api<SearchResult>(`/sessions/${s.sessionId}/search`, 'POST'); s.setResult(result); await q.invalidateQueries({ queryKey: ['session'] }); })}><Users size={19}/> Найти общее окно</Button><p className="muted">Общий подбор запускает создатель компании. Учитываем дорогу и возвращение каждого.</p>{session.data?.selectedId && <p className="selected-plan"><Check size={18}/> Общий вариант выбран: {s.result?.results.find(c => c.event.id === session.data.selectedId)?.event.title ?? session.data.selectedId}</p>}</div>}
        {busy && !s.result && s.screen === 'search' && <section className="results" aria-busy="true"><div className="section-heading"><div className="eyebrow">ПОДБИРАЕМ</div><h2>{['Ищем события…', 'Проверяем время…', 'Считаем дорогу…', 'Подбираем лучшее…'][phase]}</h2></div><div className="cards">{[0, 1, 2].map(i => <div className="event-card skeleton" key={i}><div className="sk-art"/><div className="sk-line"/><div className="sk-line short"/><div className="sk-bar"/></div>)}</div></section>}
        {resultView}
      </>}
      {s.screen === 'about' && <section className="about"><div><span className="step">1</span><h2>Задай своё окно</h2><p>Дата, свободное время, точка старта и бюджет. Можно одному или компанией до пяти человек.</p></div><div><span className="step">2</span><h2>Убедись, что успеваешь</h2><p>Считаем дорогу туда и обратно, учитываем 10 минут запаса в каждую сторону, цену и расходы на проезд. Высокий рейтинг не отменяет ограничения.</p></div><div><span className="step">3</span><h2>Выбери и поделись</h2><p>Открой источник и маршрут, сохрани план на 24 часа или пригласи друзей через MAX.</p></div>{stats.data && <article className="stats"><h3>Метрики за 7 дней <span className="muted small">живые данные, обновляются при каждом использовании</span></h3><div className="stat-grid">{[
          ['Подборов', stats.data.searches], ['Время до результата, медиана', stats.data.timeToResultSec.median !== null ? `${stats.data.timeToResultSec.median} с` : '—'],
          ['Выбор за < 3 мин', stats.data.timeToSelectSec.under3MinPercent !== null ? `${stats.data.timeToSelectSec.under3MinPercent}%` : '—'], ['Подбор → выбор', stats.data.searchToSelectionPercent !== null ? `${stats.data.searchToSelectionPercent}%` : '—'],
          ['Без результата', stats.data.noResultPercent !== null ? `${stats.data.noResultPercent}%` : '—'], ['Карточек на подбор', stats.data.cardsPerSearch ?? '—'],
          ['Компании с общим вариантом', stats.data.groupFoundPercent !== null ? `${stats.data.groupFoundPercent}%` : '—'], ['В пределах ограничений', stats.data.withinHardConstraintsPercent !== null ? `${stats.data.withinHardConstraintsPercent}%` : '—'],
          ['Нравится / нет', `${stats.data.likes} / ${stats.data.dislikes}`], ['Выход состоялся', stats.data.outings.donePercent !== null ? `${stats.data.outings.donePercent}%` : '—'],
        ].map(([label, value]) => <div className="stat" key={String(label)}><strong>{value}</strong><span>{label}</span></div>)}</div><p className="muted small">«В пределах ограничений» гарантируется движком: вариант, нарушающий время, бюджет или дорогу, не показывается (сценарии A–G в тестах).</p></article>}
        <article><h3>Что означают данные</h3><p><strong>Реальные события</strong> (по умолчанию): KudaGo и Яндекс Матрица расстояний. Неполные цены и расписания исключаем. Наличие билетов нужно уточнить у организатора.</p><p><strong>Тестовые данные</strong> (переключатель внизу страницы): синтетические события, цены, места и табличное время дороги. Это проверка сценария, а не настоящая афиша; такие карточки помечены «ТЕСТ».</p><p><strong>Расчёт:</strong> время возврата, бюджет, запас времени. <strong>Рекомендация:</strong> порядок карточек с учётом интересов. Источник и время получения указаны в карточке.</p><h3>Твои данные</h3><p>Точка старта используется только после твоего выбора. Параметры поисков и компаний удаляются через 24 часа с уборкой раз в час. Имя, идентификатор MAX, интересы и оценки — через 30 дней без активности. Мы не сохраняем номер телефона.</p><button className="text-button" onClick={() => openExternal('https://yandex.ru/legal/maps_api/')}>Условия использования Яндекс Карт <ExternalLink size={14}/></button></article></section>}
      <footer>{s.screen !== 'about' && config.data && <div className="data-switch"><span className={`mode-badge ${mode}`}><span className="status-dot"/>{mode === 'live' ? 'Реальные данные · KudaGo + Яндекс Маршруты' : 'Тестовые данные'}</span>{mode === 'live' && <span>Маршрутов сегодня: {quota.data?.used ?? '…'} из {quota.data?.limit ?? config.data.yandexDailyLimit}</span>}{liveAvailable ? <button className="text-button" disabled={busy} onClick={() => switchMode(mode === 'live' ? 'demo' : 'live')}>{mode === 'live' ? 'Переключить на тестовые данные' : 'Вернуться к реальным данным'} <ArrowRight size={13}/></button> : <span>Реальные источники на этом сервере не подключены</span>}</div>}<button onClick={() => s.setScreen('about')}>Данные и приватность <ArrowUpRight size={13}/></button></footer></div>
    </main>
    <nav className="mobile-nav"><button className={s.screen === 'search' ? 'active' : ''} onClick={() => s.setScreen('search')}><Sparkles size={21}/>Подбор</button><button className={s.screen === 'group' ? 'active' : ''} onClick={() => s.setScreen('group')}><Users size={21}/>Компания</button><button className={s.screen === 'about' ? 'active' : ''} onClick={() => s.setScreen('about')}><Info size={21}/>О проекте</button></nav>
    {notice && <div className="toast" role="status"><Check size={18}/>{notice}</div>}
    <dialog ref={dialogRef} onTouchStart={e => { swipe.current = (e.currentTarget.scrollTop <= 0 ? e.touches[0].clientY : null); }} onTouchEnd={e => { if (swipe.current !== null && e.changedTouches[0].clientY - swipe.current > 90) s.setDetail(null); swipe.current = null; }} onCancel={() => s.setDetail(null)} onClick={e => { if (e.target === e.currentTarget) s.setDetail(null); }}><div className="detail">{s.detail && <><span className="sheet-handle" aria-hidden="true"/><button className="close icon-button" aria-label="Закрыть карточку" onClick={() => s.setDetail(null)}><X size={23}/></button><div className={`detail-art ${s.detail.event.accent} ${s.detail.event.imageUrl ? 'has-photo' : ''}`}>{s.detail.event.imageUrl ? <img className="event-photo" src={s.detail.event.imageUrl} alt={s.detail.event.title}/> : <EventArt category={s.detail.event.categories[0]}/>}<span>{s.detail.event.demo ? 'Тестовые данные' : 'Реальное событие · KudaGo'}</span></div><div className="detail-body"><div className="eyebrow">{categoryNames[s.detail.event.categories[0]]}</div><h2>{s.detail.event.title}</h2><p>{s.detail.event.description}</p><div className="detail-stats"><span><Clock3 size={18}/>{hh(s.detail.startAt)}–{hh(s.detail.endAt)}</span><strong>{money(s.detail.totalPrice)} / чел.</strong></div><p className="venue"><MapPin size={17}/>{s.detail.event.venue}<br/>{s.detail.event.address}</p><div className="reasons">{s.detail.reasons.map(r => <p key={r}><Check size={16}/>{r}</p>)}</div>{s.result?.commonWindow && s.detail.members.length > 0 && <div className="detail-timelines">{s.detail.members.map((m, i) => <div key={i}>{s.detail!.members.length > 1 && <b>{m.name}</b>}<WindowTimeline window={s.result!.commonWindow!} c={s.detail!} member={i}/></div>)}</div>}{s.detail.members.map((m, i) => <div className="member-route" key={i}><b>{m.name}</b><span>Туда {m.travel.outbound} мин · обратно {m.travel.inbound} мин</span><span>Возврат {hh(m.returnAt)} · запас {m.spareMinutes} мин</span></div>)}{s.detail.warnings.map(w => <p className="warning" key={w}><Info size={14}/>{w}</p>)}<div className="source-meta">Источник: {s.detail.event.demo ? 'Тестовые данные: учебный набор ОКНО v1' : 'KudaGo'}<br/>Получено: {new Date(s.detail.event.sourceUpdatedAt).toLocaleString('ru-RU', { timeZone: 'Europe/Moscow' })}<br/>Рекомендация алгоритма · {s.detail.members.length ? `${Math.round(s.detail.score * 100)} из 100` : 'общий план без личного маршрута'}</div>
    <div className="detail-actions">{error && <div className="error" role="alert">{error}</div>}{!saved && s.result && <Button disabled={busy} onClick={() => choose(s.detail!)} stretched>Выбрать план <Check size={17}/></Button>}{saved && <div className="saved-line"><Check size={18}/> План сохранён</div>}<Button variant="secondary" stretched onClick={() => trackLink(s.detail!.routeUrl, 'route_open')}>Открыть Яндекс Карты <ArrowUpRight size={17}/></Button>{s.detail.sourceUrl && <Button variant="secondary" stretched onClick={() => trackLink(s.detail!.sourceUrl!, 'source_open')}>Источник и регистрация <ExternalLink size={17}/></Button>}{saved && <div className="share-row"><Button variant="secondary" onClick={() => share(saved.shareUrl, 'Вот наш план в ОКНО')}>Поделиться в MAX <Users size={17}/></Button><button className="icon-button" aria-label="Скопировать ссылку плана" onClick={() => copy(saved.shareUrl)}><Copy size={19}/></button></div>}</div><div className="feedback"><span>Такой вариант тебе подходит?</span><button aria-label="Нравится" onClick={() => run(async () => { await api(`/events/${s.detail!.event.id}/feedback`, 'POST', { value: 1 }); setNotice('Спасибо, оценка сохранена'); })}><Heart size={19}/></button><button aria-label="Не нравится" onClick={() => run(async () => { await api(`/events/${s.detail!.event.id}/feedback`, 'POST', { value: -1 }); setNotice('Спасибо, оценка сохранена'); })}><ThumbsDown size={19}/></button></div></div></>}</div></dialog>
  </div>;
}
function EventArt({ category }: { category: string }) { const Icon = icons[category] || Sparkles; return <div className="event-art"><span className="art-ring"/><span className="art-square"/><Icon strokeWidth={1.2}/><span className="art-plus">+</span></div>; }
function EventCard({ c, index, window, onOpen, onChoose, busy }: { c: Candidate; index: number; window: { from: string; to: string } | null; onOpen: () => void; onChoose: () => void; busy: boolean }) { return <article className="event-card" style={{ '--i': index } as CSSProperties}><button className={`card-art ${c.event.accent} ${c.event.imageUrl ? 'has-photo' : ''}`} onClick={onOpen} aria-label={`Подробнее: ${c.event.title}`}>{c.event.imageUrl ? <img className="event-photo" src={c.event.imageUrl} alt="" loading="lazy"/> : <EventArt category={c.event.categories[0]}/>}<span className="card-tag">{index === 0 ? 'Лучшее совпадение' : categoryNames[c.event.categories[0]]}</span>{c.event.demo && <span className="demo-tag">ТЕСТ</span>}</button><div className="card-content"><div className="card-time"><Clock3 size={14}/>{hh(c.startAt)}–{hh(c.endAt)}<strong>{money(c.totalPrice)}</strong></div><button className="card-title" onClick={onOpen}>{c.event.title}</button><p className="card-venue">{c.event.venue}</p><div className="card-fit"><Check size={14}/> Возврат до {hh(c.members[0].returnAt)} <span>· {c.members[0].travel.outbound} мин в пути{c.members[0].travel.modelled ? '*' : ''}</span></div>{window && <WindowTimeline window={window} c={c} compact/>}<div className="card-actions"><button className="text-button" onClick={onOpen}>Почему подходит <ArrowUpRight size={14}/></button><button className="choose" onClick={onChoose} disabled={busy}>Выбрать <ArrowRight size={15}/></button></div></div></article>; }
